var places =["Tokyo", "Istambol", "Austrelia", "Bairoot", "Zimbabwe"];
console.log (places);
places.sort();
console.log (places);
places.reverse();
console.log (places);
places.reverse();
console.log (places);
places.sort ();
console.log (places);
places.reverse();
console.log (places);