var guest = ["Asim", "Umar", "Nasir"];
console.log ("Hi dear " + guest [0] + " I would like to have the pleasure of inviting you to dinner at my home tonight, please.");
console.log ("Hi dear " + guest [1] + " I would like to have the pleasure of inviting you to dinner at my home tonight, please.");
console.log ("Hi dear " + guest [2] + " I would like to have the pleasure of inviting you to dinner at my home tonight, please.");
console.log ("Unfortunately " + guest [0] + " and " + guest [2] + " would not be able to join us at dinner");
guest [0] = "Shazib";
guest [2] = "Haroon";
console.log ("Hi dear " + guest [0] + " I would like to have the pleasure of inviting you to dinner at my home tonight, please.");
console.log ("Hi dear " + guest [1] + " I would like to have the pleasure of inviting you to dinner at my home tonight, please.");
console.log ("Hi dear " + guest [2] + " I would like to have the pleasure of inviting you to dinner at my home tonight, please.");