var a = ("cat"==="dog");
console.log (a);
var b = ("Cat" === "cat");
console.log (b);
var c = (5 === 6);
console.log (c);
var d = (7 === 7);
console.log (d);
var e = (8 > 7);
console.log (e);
var f = (8 < 7);
console.log (f);
var g = (9 >= 9);
console.log (g);
var h = (9 >= 10);
console.log (h);
var i = (9 <= 9);
console.log (i);
var j = (9 <= 10);
console.log (j);
var k = ("cat" === "cat" && "dog" === "DOG");
console.log (k);
var l = ("cat" === "cat" || "dog" === "DOG");
console.log (l);
var m = [5, 4, 9, 11];
console.log (m.includes(4));
console.log (m.includes(3));

